version: "2.4"
services:
  importer:
    image: gofwd/openvas-importer
    volumes:
      - cert_data_vol:/target/cert
      - notus_data_vol:/target/notus
      - psql_data_vol:/target/psql
      - scap_data_vol:/target/scap
      - vt_data_vol:/target/vt

  # cert-bund-data:
  #   image: greenbone/cert-bund-data
  #   volumes:
  #     - cert_data_vol:/mnt

  # dfn-cert-data:
  #   image: greenbone/dfn-cert-data
  #   volumes:
  #     - cert_data_vol:/mnt
  #   depends_on:
  #     - cert-bund-data

  # notus-data:
  #   image: greenbone/notus-data
  #   volumes:
  #     - notus_data_vol:/mnt

  # scap-data:
  #   image: greenbone/scap-data
  #   volumes:
  #     - scap_data_vol:/mnt

  # vulnerability-tests:
  #   image: greenbone/vulnerability-tests
  #   environment:
  #     STORAGE_PATH: /var/lib/openvas/22.04/vt-data/nasl
  #   volumes:
  #     - vt_data_vol:/mnt

  gpg-data:
    image: greenbone/gpg-data
    volumes:
      - gpg_data_vol:/mnt

  data-objects:
    image: greenbone/data-objects
    volumes:
      - data_objects_vol:/mnt

  report-formats:
    image: greenbone/report-formats
    volumes:
      - data_objects_vol:/mnt
    depends_on:
      - data-objects

  redis-server:
    image: greenbone/redis-server
    restart: unless-stopped
    volumes:
      - redis_socket_vol:/run/redis/

  pg-gvm:
    image: greenbone/pg-gvm:stable
    restart: unless-stopped
    volumes:
      - psql_data_vol:/var/lib/postgresql
      - psql_socket_vol:/var/run/postgresql

  gvmd:
    image: greenbone/gvmd:stable
    restart: unless-stopped
    volumes:
      - cert_data_vol:/var/lib/gvm/cert-data
      - gvmd_data_vol:/var/lib/gvm
      - psql_data_vol:/var/lib/postgresql
      - scap_data_vol:/var/lib/gvm/scap-data/
      - vt_data_vol:/var/lib/openvas/plugins
      - data_objects_vol:/var/lib/gvm/data-objects/gvmd
      - gvmd_socket_vol:/run/gvmd
      - ospd_openvas_socket_vol:/run/ospd
      - psql_socket_vol:/var/run/postgresql
    container_name: gvmd
    depends_on:
      pg-gvm:
        condition: service_started
      # scap-data:
      #   condition: service_started
      # cert-bund-data:
      #   condition: service_started
      # dfn-cert-data:
      #   condition: service_started
      data-objects:
        condition: service_started
      report-formats:
        condition: service_started

  gsa:
    image: greenbone/gsa:stable
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - gvmd_socket_vol:/run/gvmd
    depends_on:
      - gvmd

  ospd-openvas:
    image: greenbone/ospd-openvas:stable
    restart: unless-stopped
    init: true
    hostname: ospd-openvas.local
    cap_add:
      - NET_ADMIN # for capturing packages in promiscuous mode
      - NET_RAW # for raw sockets e.g. used for the boreas alive detection
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    command:
      [
        "ospd-openvas",
        "-f",
        "--config",
        "/etc/gvm/ospd-openvas.conf",
        "--mqtt-broker-address",
        "mqtt-broker",
        "--notus-feed-dir",
        "/var/lib/notus/advisories",
        "-m",
        "666"
      ]
    volumes:
      - gpg_data_vol:/etc/openvas/gnupg
      - vt_data_vol:/var/lib/openvas/plugins
      - notus_data_vol:/var/lib/notus
      - ospd_openvas_socket_vol:/run/ospd
      - redis_socket_vol:/run/redis/
    depends_on:
      redis-server:
        condition: service_started
      gpg-data:
        condition: service_started
      # vulnerability-tests:
      #   condition: service_started

  mqtt-broker:
    restart: unless-stopped
    image: greenbone/mqtt-broker
    ports:
      - 1883:1883
    networks:
      default:
        aliases:
          - mqtt-broker
          - broker

  notus-scanner:
    restart: on-failure
    image: greenbone/notus-scanner:stable
    volumes:
      - notus_data_vol:/var/lib/notus
      - gpg_data_vol:/etc/openvas/gnupg
    environment:
      NOTUS_SCANNER_MQTT_BROKER_ADDRESS: mqtt-broker
      NOTUS_SCANNER_PRODUCTS_DIRECTORY: /var/lib/notus/products
    depends_on:
      - mqtt-broker
      - gpg-data
      # - vulnerability-tests

  # gvm-tools:
  #   image: greenbone/gvm-tools
  #   volumes:
  #     - gvmd_socket_vol:/run/gvmd
  #     - ospd_openvas_socket_vol:/run/ospd
  #   depends_on:
  #     - gvmd
  #     - ospd-openvas

  debian:
    image: gofwd/lab-ssh
    ports:
      - "2222:22"
    restart: unless-stopped

  juice-shop:
    image: gofwd/juice-shop
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  cert_data_vol:
  gpg_data_vol:
  gvmd_data_vol:
  notus_data_vol:
  psql_data_vol:
  scap_data_vol:
  vt_data_vol:
  data_objects_vol:
  gvmd_socket_vol:
  ospd_openvas_socket_vol:
  psql_socket_vol:
  redis_socket_vol:
