version: "2.4"
services:
  debian:
    build: .
    ports:
      - 2222:22
    restart: unless-stopped

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - 3000:3000
    restart: unless-stopped
