version: "2.4"
services:
  debian:
    build: .
    ports:
      - "2222:22"
    restart: unless-stopped

  juice-shop:
    image: gofwd/juice-shop
    ports:
      - "80:3000"
    restart: unless-stopped
